import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Arabic, Vazirmatn } from "next/font/google";
import "./globals.css";
import TopNavbar from "./components/Nav/TopNavbar";
import MobileNavbar from "./components/Nav/BottomNavbar";
import ClientLayoutWrapper from "./ClientLayoutWrapper";
import { SettingsInitializer } from "@/components/settings-initializer";

const vazirmatn = Vazirmatn({
  subsets: ['arabic', 'latin'],
  display: 'swap',
  variable: '--font-vazirmatn'
})

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ['arabic'],
  display: 'swap',
  variable: '--font-noto-arabic'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {

  const { lang } = await params
  return (
    <html lang="en" className={`scrollbar-hide ${vazirmatn.variable}`}>
      <body
        className={`${vazirmatn.className} antialiased`}
      >
        <SettingsInitializer lang={lang}>
          <ClientLayoutWrapper lang={lang}>
            <TopNavbar />
            {children}
            <MobileNavbar/>
          </ClientLayoutWrapper>
        </SettingsInitializer>
      </body>
    </html>
  );
}
